services:
  api:
    image: ghcr.io/get-to-the-point/unicat-api:latest
    container_name: unicat-api
    ports:
      - "8081:8080"
    networks:
      - unicat-network
    env_file:
      - .env

  database:
    image: postgres:15-alpine
    container_name: unicat-database
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - unicat-network

volumes:
  postgres_data:

networks:
  unicat-network:
    driver: bridge