services:
  api:
    image: ghcr.io/get-to-the-point/ai-news-api:latest
    container_name: ai-news-api
    ports:
      - "8081:8080"
    networks:
      - ai-news-network
    env_file:
      - .env

  database:
    image: postgres:15-alpine
    container_name: ai-news-database
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - ai-news-network

volumes:
  postgres_data:

networks:
  ai-news-network:
    driver: bridge