spring:
  application:
    name: ai-news-api
  config:
    import: classpath:core/application-oauth.yml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /

security:
  headers:
    frame-options: ${SPRING_SECURITY_HEADERS_FRAME_OPTIONS:DENY}

ai-news:
  jwt:
    secret: ${SPRING_AI_NEWS_JWT_SECRET}