spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 10000

logging:
  loki:
    url: ${LOKI_URL:https://loki.xiyo.dev/loki/api/v1/push}
  level:
    root: INFO
