spring:
  application:
    name: unicat-api
  config:
    import: classpath:core/application-oauth.yml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /

security:
  headers:
    frame-options: ${SPRING_SECURITY_HEADERS_FRAME_OPTIONS:DENY}

app:
  jwt:
    private-key: ${APP_JWT_PRIVATE_KEY}
    public-key: ${APP_JWT_PUBLIC_KEY}
    key-id: ${APP_JWT_KEY_ID}

server:
  port: 443
  ssl:
    key-store: ${APP_SSL_KEY_STORE}
    key-store-type: ${APP_SSL_KEY_STORE_TYPE:PKCS12}
    key-store-password: ${APP_SSL_KEY_STORE_PASSWORD}
    key-alias: ${APP_SSL_KEY_ALIAS}

  # JSESSIONID 쿠키 발급이 안되도록 하기 위한 장치
  servlet:
    session:
      tracking-modes: ssl