spring:
  application:
    name: unicat-api
  config:
    import: classpath:core/application-oauth.yml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    locale: ko
    locale-resolver: accept-header
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}

springdoc:
  swagger-ui:
    path: /

app:
  jwt:
    private-key: ${APP_JWT_PRIVATE_KEY:classpath:unicat.day/unicat.day.key}
    public-key: ${APP_JWT_PUBLIC_KEY:classpath:unicat.day/unicat.day.pub}
    key-id: ${APP_JWT_KEY_ID:rsa-key-id}
    cookie:
      name: Authorization
      domain: ${APP_JWT_COOKIE_DOMAIN:unicat.day}
      path: /
      secure: ${APP_JWT_COOKIE_SECURE:true}
      httpOnly: ${APP_JWT_COOKIE_HTTP_ONLY:true}
      sameSite: ${APP_JWT_COOKIE_SAME_SITE:Lax}
      maxAge: ${APP_JWT_COOKIE_MAX_AGE:604800}
  api:
    protocol: https
    domain: api.unicat.day
    port: 443
  toss:
    client-key: ${APP_TOSS_CLIENT_KEY:test_ck_D5GePWvyJnrK0W0k6q8gLzN97Eoq} # 토스가 공개적으로 제공하는 키
    secret-key: ${APP_TOSS_SECRET_KEY:test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R} # 토스가 공개적으로 제공하는 키
    approve-url: ${APP_TOSS_APPROVE_URL:https://api.tosspayments.com/v1/billing}
    billing-url: ${APP_TOSS_BILLING_URL:https://api.tosspayments.com/v1/billing/authorizations/issue}
  frontend:
    url: ${APP_FRONTEND_URL:https://unicat.day}
  filestorage:
    local-root: ${APP_FILESTORAGE_LOCAL_ROOT:${user.home}/unicat}
  cors:
    allowed-origins:
      - ${APP_CORS_ALLOWED_ORIGINS:https://unicat.day}
    allowed-methods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
    allowed-headers: [ "*" ]
    allow-credentials: true
    max-age: 3600
  openai:
    script:
      prompt: ${SCRIPT_AI_PROMPT:"다음 스크립트를 읽고, '%s'에 맞춰 문장을 자연스럽게 다듬고 필요한 보충 내용을 추가해줘.%n%n원본 스크립트:%n%s"}
      model: ${SCRIPT_AI_MODEL:gpt-4o-mini}
      temperature: ${SCRIPT_AI_TEMPERATURE:0.7}
    image:
      prompt: ${IMAGE_AI_PROMPT:"다음 스크립트를 읽고, ‘%s’스타일로 아름답고 퀄리티 좋은 정밀한 이미지를 만들어줘. 부족한 부분이 있다면 알아서 채워줘. %n%n스크립트:%n%s"}
      model: ${IMAGE_AI_MODEL:dall-e-3}
      quality: ${IMAGE_AI_QUALITY:hd}
    auto:
      prompt: ${AUTO_AI_PROMPT:"다음의 주제를 보고 %s에 맞춰서 5개의 섹션으로 나누어서 한 섹션마다 1~2문장의 스크립트를 만들어줘. 그걸 모두 합쳐서 짧은 영상으로 만들거야. %n%n주제:%s"}
  media:
    ffmpeg:
      path: ${APP_MEDIA_FFMPEG_PATH:ffmpeg}
  supertone:
    api-key: ${APP_SUPERTONE_API_KEY}
    default-voice-id: ${APP_SUPERTONE_DEFAULT_VOICE_ID:d9Hi4iF7HEXpGWo6cC5YbZ}

server:
  port: 443
  ssl:
    key-store: ${APP_SSL_KEY_STORE:classpath:unicat.day/unicat.day.p12}
    key-store-type: ${APP_SSL_KEY_STORE_TYPE:PKCS12}
    key-store-password: ${APP_SSL_KEY_STORE_PASSWORD:unicat.day}
    key-alias: ${APP_SSL_KEY_ALIAS:unicat.day}
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always