spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        show_sql: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG

app:
  jwt:
    secret: 879PP1tB6p2StH4oVAtvME7nmqM1eGCYrQpIskegR2fFsHa9kaftJpA6CqGs3aQCzszcdvSZRxWwO9FsS5s78Q==
    cookie:
      name: Authorization
      domain: unicat.day
      path: /
      secure: false
      httpOnly: true
      sameSite: Lax
      maxAge: 604800
    expiration: 604800000

  api:
    protocol: https
    domain: api.unicat.day
    port: 8080

  ui:
    protocol: https
    domain: unicat.day
    port: 3000

server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: ""
    key-alias: unicat.day