filestorage:
  minio:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    access-key-id: ${MINIO_ACCESS_KEY_ID:test-minio}
    secret-access-key: ${MINIO_SECRET_KEY:test-minio}
    bucket: ${MINIO_BUCKET:unicat}