spring:
  application:
    name: unicat-api
  config:
    import: classpath:core/application-oauth.yml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  swagger-ui:
    path: /

app:
  jwt:
    private-key: ${APP_JWT_PRIVATE_KEY}
    public-key: ${APP_JWT_PUBLIC_KEY}
    key-id: ${APP_JWT_KEY_ID}

server:
  port: 443
  ssl:
    key-store: ${APP_SSL_KEY_STORE}
    key-store-type: ${APP_SSL_KEY_STORE_TYPE:PKCS12}
    key-store-password: ${APP_SSL_KEY_STORE_PASSWORD}
    key-alias: ${APP_SSL_KEY_ALIAS}

youtube:
  api:
    key: ${YOUTUBE_API_KEY:AIzaSyD98eK0PRdCvE9hr_7qLIwhriuxdM5mUZc}