spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            redirect-uri: http://api.ai-news.com:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email